
[bumpver]
current_version = "v1.0.2"
version_pattern = "vMAJOR.MINOR.PATCH"
commit_message = "bump version from {old_version} to {new_version}"
tag_message = "{new_version}"
tag_scope = "default"
pre_commit_hook = ""
post_commit_hook = ""
commit = true
tag = false
push = false

[bumpver.file_patterns]
"pyproject.toml" = [
  'version = "{pep440_version}"',
]
"apps/version/__init__.py" = [
  '__version__ = "v{version}"',
]
"README.md" = [
  "Current version: v{version}",
]
"bumpver.toml" = [
  'current_version = "v{version}"',
]